#!/usr/bin/env python3
"""
Generate stub BUILD.bazel files for MongoDB's enterprise module.

The community source tarball doesn't include the proprietary enterprise module,
but several BUILD targets unconditionally reference enterprise packages (e.g. the
core_headers_library in src/BUILD.bazel). This script creates minimal stub
BUILD.bazel files that define empty filegroup targets so that Bazel analysis
can succeed for a community-only build with --build_enterprise=False.
"""

import os

# Map of every enterprise package path to the target names it must export.
# Extracted from src/BUILD.bazel and the root BUILD.bazel at tag r8.0.23.
ENTERPRISE_STUBS = {
    "src/mongo/db/modules/enterprise": [
        "enterprise_global_hdrs",
        "mongocryptd",
        "dist",
        "dist-test",
        "mongo_crypt",
        "mongo_crypt_shlib_test",
    ],
    "src/mongo/db/modules/enterprise/distsrc": [
        "enterprise_license",
        "windows_notices",
    ],
    "src/mongo/db/modules/enterprise/autogenerated_targets": [
        "mongo_integration_test",
    ],
    "src/mongo/db/modules/enterprise/docs": ["docs_global_hdrs"],
    "src/mongo/db/modules/enterprise/docs/fle": ["fle_global_hdrs"],
    "src/mongo/db/modules/enterprise/docs/testing": ["testing_global_hdrs"],
    "src/mongo/db/modules/enterprise/src": ["src_global_hdrs"],
    "src/mongo/db/modules/enterprise/src/audit": [
        "audit_commands_idl_gen",
        "audit_config_idl_gen",
        "audit_decryptor_options_idl_gen",
        "audit_event_type_idl_gen",
        "audit_global_hdrs",
        "audit_header_options_idl_gen",
        "audit_options_idl_gen",
    ],
    "src/mongo/db/modules/enterprise/src/audit/logger": ["logger_global_hdrs"],
    "src/mongo/db/modules/enterprise/src/audit/mongo": ["mongo_global_hdrs"],
    "src/mongo/db/modules/enterprise/src/audit/ocsf": [
        "ocsf_audit_events_idl_gen",
        "ocsf_global_hdrs",
    ],
    "src/mongo/db/modules/enterprise/src/encryptdb": [
        "decrypt_tool_options_idl_gen",
        "encryptdb_global_hdrs",
        "encryption_key_manager_idl_gen",
        "encryption_options_idl_gen",
        "keystore_metadata_idl_gen",
        "log_redact_options_idl_gen",
    ],
    "src/mongo/db/modules/enterprise/src/fcbis": ["fcbis_global_hdrs"],
    "src/mongo/db/modules/enterprise/src/fips": [
        "fips_flag_client_idl_gen",
        "fips_flag_server_idl_gen",
        "fips_global_hdrs",
    ],
    "src/mongo/db/modules/enterprise/src/fle": ["fle_global_hdrs"],
    "src/mongo/db/modules/enterprise/src/fle/commands": ["commands_global_hdrs"],
    "src/mongo/db/modules/enterprise/src/fle/lib": ["lib_global_hdrs"],
    "src/mongo/db/modules/enterprise/src/fle/query_analysis": ["query_analysis_global_hdrs"],
    "src/mongo/db/modules/enterprise/src/fle/shell": ["shell_global_hdrs"],
    "src/mongo/db/modules/enterprise/src/hot_backups": [
        "backup_cursor_parameters_idl_gen",
        "document_source_backup_file_idl_gen",
        "hot_backups_global_hdrs",
    ],
    "src/mongo/db/modules/enterprise/src/inmemory": [
        "inmemory_global_hdrs",
        "inmemory_global_options_idl_gen",
    ],
    "src/mongo/db/modules/enterprise/src/kerberos": [
        "kerberos_global_hdrs",
        "kerberos_tool_options_idl_gen",
    ],
    "src/mongo/db/modules/enterprise/src/kmip": [
        "kmip_global_hdrs",
        "kmip_options_idl_gen",
    ],
    "src/mongo/db/modules/enterprise/src/ldap": [
        "ldap_global_hdrs",
        "ldap_options_idl_gen",
        "ldap_options_mongod_idl_gen",
        "ldap_parameters_idl_gen",
        "ldap_runtime_parameters_idl_gen",
        "ldap_tool_options_idl_gen",
        "ldap_user_cache_poller_idl_gen",
    ],
    "src/mongo/db/modules/enterprise/src/ldap/connections": ["connections_global_hdrs"],
    "src/mongo/db/modules/enterprise/src/ldap/name_mapping": ["name_mapping_global_hdrs"],
    "src/mongo/db/modules/enterprise/src/live_import": [
        "collection_properties_idl_gen",
        "live_import_global_hdrs",
    ],
    "src/mongo/db/modules/enterprise/src/live_import/commands": [
        "commands_global_hdrs",
        "export_collection_idl_gen",
        "import_collection_idl_gen",
        "vote_commit_import_collection_idl_gen",
    ],
    "src/mongo/db/modules/enterprise/src/magic_restore": [
        "magic_restore_global_hdrs",
        "magic_restore_options_idl_gen",
        "magic_restore_structs_idl_gen",
    ],
    "src/mongo/db/modules/enterprise/src/queryable": ["queryable_global_hdrs"],
    "src/mongo/db/modules/enterprise/src/queryable/blockstore": ["blockstore_global_hdrs"],
    "src/mongo/db/modules/enterprise/src/queryable/queryable_wt": [
        "queryable_global_options_idl_gen",
        "queryable_wt_global_hdrs",
    ],
    "src/mongo/db/modules/enterprise/src/sasl": [
        "auth_delay_idl_gen",
        "oidc_commands_idl_gen",
        "oidc_parameters_idl_gen",
        "sasl_aws_server_options_idl_gen",
        "sasl_global_hdrs",
    ],
    "src/mongo/db/modules/enterprise/src/scripts": ["scripts_global_hdrs"],
    "src/mongo/db/modules/enterprise/src/serverless": [
        "mongoqd_options_idl_gen",
        "serverless_global_hdrs",
    ],
    "src/mongo/db/modules/enterprise/src/streams": ["streams_global_hdrs"],
    "src/mongo/db/modules/enterprise/src/streams/commands": [
        "commands_global_hdrs",
        "stream_ops_idl_gen",
    ],
    "src/mongo/db/modules/enterprise/src/streams/exec": [
        "checkpoint_data_idl_gen",
        "common_idl_gen",
        "config_idl_gen",
        "exec_global_hdrs",
        "exec_internal_idl_gen",
        "stages_idl_gen",
    ],
    "src/mongo/db/modules/enterprise/src/streams/exec/checkpoint": ["checkpoint_global_hdrs"],
    "src/mongo/db/modules/enterprise/src/streams/exec/tests": ["tests_global_hdrs"],
    "src/mongo/db/modules/enterprise/src/streams/management": ["management_global_hdrs"],
    "src/mongo/db/modules/enterprise/src/streams/management/tests": ["tests_global_hdrs"],
    "src/mongo/db/modules/enterprise/src/streams/tools": ["tools_global_hdrs"],
    "src/mongo/db/modules/enterprise/src/streams/util": ["util_global_hdrs"],
    "src/mongo/db/modules/enterprise/src/streams/util/tests": ["tests_global_hdrs"],
    "src/mongo/db/modules/enterprise/src/util": ["util_global_hdrs"],
    "src/mongo/db/modules/enterprise/src/workloads": ["workloads_global_hdrs"],
    "src/mongo/db/modules/enterprise/src/workloads/streams": ["streams_global_hdrs"],
}


def generate_build_content(targets):
    """Generate a BUILD.bazel file with empty filegroup stubs."""
    lines = [
        '# AUTO-GENERATED stub for community builds (no enterprise module).',
        'package(default_visibility = ["//visibility:public"])',
        "",
    ]
    for target in sorted(targets):
        lines.append(f'filegroup(name = "{target}", srcs = [])')
    return "\n".join(lines) + "\n"


def main():
    for pkg_path, targets in ENTERPRISE_STUBS.items():
        os.makedirs(pkg_path, exist_ok=True)
        build_file = os.path.join(pkg_path, "BUILD.bazel")
        if not os.path.exists(build_file):
            with open(build_file, "w") as f:
                f.write(generate_build_content(targets))
            print(f"  Created {build_file} ({len(targets)} stub targets)")
        else:
            print(f"  Skipped {build_file} (already exists)")


if __name__ == "__main__":
    print("Generating enterprise module stubs for community build...")
    main()
    print("Done.")
